name: example
description: A project that showcases usage of swagger_parser
publish_to: none
environment:
  sdk: ^3.0.0

dependencies:
  dart_mappable: ^4.1.0
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.7
  carapacik_lints: ^1.4.2
  dart_mappable_builder: ^4.1.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.5
  swagger_parser:
    path:
      ../
